CREATE TABLE member
(
    id INT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(100) NOT NULL,
    pw VARCHAR(100) NOT NULL,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(20) NOT NULL,
    contact VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT MEMBER_PK PRIMARY KEY(id)
)